name: cicd-workflow with slack integration
on:
  push:
    branches: [ "master" ]
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: act10ns/slack@v2
        with:
          status: starting
          channel: '#mar-2024-weekend-batch'
          message: Starting Docker Build image...
        if: always()

      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn install -f MyWebApp/pom.xml

      - uses: act10ns/slack@v2
        with:
          channel: '#mar-2024-weekday-batch'
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()
